table 'datos_eventos_detectados (2)'
	lineageTag: d45dbb30-7060-4e5c-888d-b9fd518f1d83

	column E
		dataType: int64
		formatString: 0
		lineageTag: ea857ea4-9e0b-42e5-b574-275a884f64fd
		summarizeBy: sum
		sourceColumn: E

		annotation SummarizationSetBy = Automatic

	column N
		dataType: int64
		formatString: 0
		lineageTag: d355be74-7a2c-4b40-9e94-a6a959154a51
		summarizeBy: sum
		sourceColumn: N

		annotation SummarizationSetBy = Automatic

	column Z
		dataType: int64
		formatString: 0
		lineageTag: df3d4367-2aaa-4dd6-96e6-00de11227c19
		summarizeBy: sum
		sourceColumn: Z

		annotation SummarizationSetBy = Automatic

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: 059fe882-1bba-4a24-9aff-604449309222
		summarizeBy: none
		sourceColumn: Fecha

		variation Variación
			isDefault
			relationship: 188aae75-91a1-4619-8a4c-2f0ab63a2ca7
			defaultHierarchy: LocalDateTable_4934af68-47c1-40aa-8675-a7e742c6df8a.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Hora
		dataType: dateTime
		formatString: Long Time
		lineageTag: 2e8f8225-37c3-4963-bd8e-05d1b6417c8e
		summarizeBy: none
		sourceColumn: Hora

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Magnitud_Filtrada_MI
		dataType: int64
		formatString: 0
		lineageTag: e3d0a949-a0a7-42d8-947d-647736ccfa7f
		summarizeBy: sum
		sourceColumn: Magnitud_Filtrada_MI

		annotation SummarizationSetBy = Automatic

	column Max_Amplitud_Filtrada
		dataType: int64
		formatString: 0
		lineageTag: bb8b82d3-f5eb-4b7f-b1f7-375a1c3e12ba
		summarizeBy: sum
		sourceColumn: Max_Amplitud_Filtrada

		annotation SummarizationSetBy = Automatic

	column Ml_Calculada
		dataType: int64
		formatString: 0
		lineageTag: 6d4e1b8b-38c1-46ff-a467-244a3bf85eb8
		summarizeBy: sum
		sourceColumn: Ml_Calculada

		annotation SummarizationSetBy = Automatic

	column Fin_Evento
		dataType: dateTime
		formatString: General Date
		lineageTag: 6b3f7ce9-1c21-4aa8-abe0-e6dc0907aa45
		summarizeBy: none
		sourceColumn: Fin_Evento

		variation Variación
			isDefault
			relationship: d149d949-49bb-4b35-bf60-2b9f3b38a8e2
			defaultHierarchy: LocalDateTable_be5ab121-b0de-44c2-9468-74dfc4d8153e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

	column Duracion_Evento_s
		dataType: int64
		formatString: 0
		lineageTag: 9ae14b27-5812-479f-958c-c35d34b81ce0
		summarizeBy: sum
		sourceColumn: Duracion_Evento_s

		annotation SummarizationSetBy = Automatic

	partition 'datos_eventos_detectados (2)' = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("F:\gustavo\Desktop\PracticasProfecionalizantes_1_2025\datos_eventos_detectados.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"E", Int64.Type}, {"N", Int64.Type}, {"Z", Int64.Type}, {"Fecha", type date}, {"Hora", type time}, {"Magnitud_Filtrada_MI", Int64.Type}, {"Max_Amplitud_Filtrada", Int64.Type}, {"Ml_Calculada", Int64.Type}, {"Fin_Evento", type datetime}, {"Duracion_Evento_s", Int64.Type}})
				in
				    #"Tipo cambiado"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

