table 'datos_eventos_detectados (2)'
	lineageTag: d45dbb30-7060-4e5c-888d-b9fd518f1d83

	column E
		dataType: string
		lineageTag: ea857ea4-9e0b-42e5-b574-275a884f64fd
		summarizeBy: none
		sourceColumn: E

		annotation SummarizationSetBy = Automatic

	column N
		dataType: string
		lineageTag: d355be74-7a2c-4b40-9e94-a6a959154a51
		summarizeBy: none
		sourceColumn: N

		annotation SummarizationSetBy = Automatic

	column Max_Amplitud_Filtrada
		dataType: string
		lineageTag: bb8b82d3-f5eb-4b7f-b1f7-375a1c3e12ba
		summarizeBy: none
		sourceColumn: Max_Amplitud_Filtrada

		annotation SummarizationSetBy = Automatic

	column Duracion_Evento_s
		dataType: string
		lineageTag: 9ae14b27-5812-479f-958c-c35d34b81ce0
		summarizeBy: none
		sourceColumn: Duracion_Evento_s

		annotation SummarizationSetBy = Automatic

	column Fecha_Evento
		dataType: string
		lineageTag: b33d78ac-b202-48d4-afba-4fc948340402
		summarizeBy: none
		sourceColumn: Fecha_Evento

		annotation SummarizationSetBy = Automatic

	column Hora_Inicio_Evento
		dataType: string
		lineageTag: 70484f03-c9bf-4f0b-9f01-9f3206d4cbc0
		summarizeBy: none
		sourceColumn: Hora_Inicio_Evento

		annotation SummarizationSetBy = Automatic

	column Hora_Fin_Evento
		dataType: string
		lineageTag: fa414c3d-1b80-4cda-935d-b74b19534ec0
		summarizeBy: none
		sourceColumn: Hora_Fin_Evento

		annotation SummarizationSetBy = Automatic

	column Ml_Calculada_Simplificada
		dataType: string
		lineageTag: 0fe969eb-e133-4c63-9d29-3d9cee0ecd34
		summarizeBy: none
		sourceColumn: Ml_Calculada_Simplificada

		annotation SummarizationSetBy = Automatic

	column Fecha_Lectura
		dataType: string
		lineageTag: 8bd85090-d75d-440a-9718-31d2c4261760
		summarizeBy: none
		sourceColumn: Fecha_Lectura

		annotation SummarizationSetBy = Automatic

	column Hora_Lectura
		dataType: string
		lineageTag: 5e7ef374-43ae-4b29-9a18-dd95f0ea3ece
		summarizeBy: none
		sourceColumn: Hora_Lectura

		annotation SummarizationSetBy = Automatic

	partition 'datos_eventos_detectados (2)' = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("F:\gustavo\Desktop\PracticasProfecionalizantes_1_2025\datos_eventos_detectados.csv"),[Delimiter=",", Columns=10, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true])
				in
				    #"Encabezados promovidos"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

