table datos_eventos_detectados
	lineageTag: ae8241cd-eb18-4077-86d8-1dc5e0117e19

	measure TOTAL_EVENTOS = COUNT(datos_eventos_detectados[Índice])
		formatString: 0
		lineageTag: 6ddf353f-a737-4fc7-b072-6a0d0d663797

	column Fecha_Evento
		dataType: dateTime
		formatString: Long Date
		lineageTag: a458fb53-5ba6-48cc-b58a-9e1db8a4c4ea
		summarizeBy: none
		sourceColumn: Fecha_Evento

		variation Variación
			isDefault
			relationship: febce2be-2618-4729-b6c4-97a2aade20f4
			defaultHierarchy: LocalDateTable_6c97138f-bc26-4f49-8cc6-aae090755174.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Hora_Inicio_Evento
		dataType: dateTime
		formatString: Long Time
		lineageTag: 8e75bdfd-77c7-4ee9-b684-debc25e061e8
		summarizeBy: none
		sourceColumn: Hora_Inicio_Evento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Hora_Fin_Evento
		dataType: dateTime
		formatString: Long Time
		lineageTag: 6966a909-c67f-4b2d-b6f6-b657ee4c0629
		summarizeBy: none
		sourceColumn: Hora_Fin_Evento

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Duracion_Evento_s
		dataType: int64
		formatString: 0
		lineageTag: 35f1e98d-3e56-4aec-a00c-f468f49f30d6
		summarizeBy: sum
		sourceColumn: Duracion_Evento_s

		annotation SummarizationSetBy = Automatic

	column Max_Amplitud_Filtrada
		dataType: int64
		formatString: 0
		lineageTag: b1f4de3b-b20d-4555-b0da-bd486417541e
		summarizeBy: sum
		sourceColumn: Max_Amplitud_Filtrada

		annotation SummarizationSetBy = Automatic

	column Fecha_Lectura
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8e9e6b0f-32fc-4e92-b215-0816e8796610
		summarizeBy: none
		sourceColumn: Fecha_Lectura

		variation Variación
			isDefault
			relationship: e32633e8-5653-4c78-af4e-a1ba3a69b382
			defaultHierarchy: LocalDateTable_266ef169-b07d-4557-9f95-33c72d535f5e.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Hora_Lectura
		dataType: dateTime
		formatString: Long Time
		lineageTag: 7a41afe7-8ee2-4fa2-bfca-5729c2f5e616
		summarizeBy: none
		sourceColumn: Hora_Lectura

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column E
		dataType: int64
		formatString: 0
		lineageTag: 14da387d-4647-4108-9d0f-fba7383673de
		summarizeBy: sum
		sourceColumn: E

		annotation SummarizationSetBy = Automatic

	column N
		dataType: int64
		formatString: 0
		lineageTag: 092a4f67-e710-43fd-86a5-2693abb9d827
		summarizeBy: sum
		sourceColumn: N

		annotation SummarizationSetBy = Automatic

	column Z
		dataType: int64
		formatString: 0
		lineageTag: e59be836-85f6-44ac-be78-0311b619591a
		summarizeBy: sum
		sourceColumn: Z

		annotation SummarizationSetBy = Automatic

	column Magnitude
		dataType: int64
		formatString: 0
		lineageTag: f3fbb5d1-f29f-4ecc-a3ca-1d848d6a374d
		summarizeBy: sum
		sourceColumn: Magnitude

		annotation SummarizationSetBy = Automatic

	column Magnitude_Filtered
		dataType: int64
		formatString: 0
		lineageTag: feca2d2e-268e-4d0e-ad4b-5827b1f9f4bc
		summarizeBy: sum
		sourceColumn: Magnitude_Filtered

		annotation SummarizationSetBy = Automatic

	column Índice
		dataType: int64
		formatString: 0
		lineageTag: 2aee239c-831d-4d30-b177-eebb5314c4c9
		summarizeBy: none
		sourceColumn: Índice

		annotation SummarizationSetBy = Automatic

	column DURACION
		dataType: string
		lineageTag: cdcfe25a-7eee-442d-9dd1-825636566dea
		summarizeBy: none
		sourceColumn: DURACION

		annotation SummarizationSetBy = Automatic

	partition datos_eventos_detectados = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("F:\gustavo\Desktop\PracticasProfecionalizantes_1_2025\datos_eventos_detectados.csv"),[Delimiter=",", Columns=12, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"Fecha_Evento", type date}, {"Hora_Inicio_Evento", type time}, {"Hora_Fin_Evento", type time}, {"Duracion_Evento_s", Int64.Type}, {"Max_Amplitud_Filtrada", Int64.Type}, {"Fecha_Lectura", type date}, {"Hora_Lectura", type time}, {"E", Int64.Type}, {"N", Int64.Type}, {"Z", Int64.Type}, {"Magnitude", Int64.Type}, {"Magnitude_Filtered", Int64.Type}}),
				    #"Índice agregado" = Table.AddIndexColumn(#"Tipo cambiado", "Índice", 1, 1, Int64.Type),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Índice agregado", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
				    #"Personalizada agregada" = Table.AddColumn(#"Filas en blanco eliminadas", "DURACION", each Duration.TotalSeconds([Hora_Fin_Evento] - [Hora_Inicio_Evento])),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Personalizada agregada",{{"DURACION", type text}})
				in
				    #"Tipo cambiado1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

