table MAP
	lineageTag: 96c0369c-293c-4cf3-9497-e7d69b1c397b

	column ID
		dataType: string
		lineageTag: 30757cb4-2ef2-46af-b860-cb1e975cb17d
		dataCategory: Address
		summarizeBy: none
		sourceColumn: ID

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Año
		dataType: string
		lineageTag: 77b910c7-93b7-4e5a-ab49-d797688ad24d
		summarizeBy: none
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: 4131a324-5824-47a1-905c-449d614c5983
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Día
		dataType: string
		lineageTag: 22f61868-88fd-4b69-9fdc-1240316a3b71
		summarizeBy: none
		sourceColumn: Día

		annotation SummarizationSetBy = Automatic

	column HH
		dataType: int64
		formatString: 0
		lineageTag: 58e2efa0-4ec5-42bc-87d8-81637d9030fb
		summarizeBy: sum
		sourceColumn: HH

		annotation SummarizationSetBy = Automatic

	column MM
		dataType: string
		lineageTag: 18f0de04-7a6f-49ff-8ea8-57acffe8c75f
		summarizeBy: none
		sourceColumn: MM

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column Seg
		dataType: string
		lineageTag: dd352904-00ff-4922-9385-d9e38e6dce20
		summarizeBy: none
		sourceColumn: Seg

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

	column 'seg.1'
		dataType: double
		lineageTag: 0b73ef1e-6f3c-4935-96dd-21a35444046b
		summarizeBy: sum
		sourceColumn: seg.1

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Latitud
		dataType: double
		lineageTag: dd7eda93-99c1-4207-a008-021c188aa1b5
		dataCategory: Latitude
		summarizeBy: none
		sourceColumn: Latitud

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Longitud
		dataType: double
		lineageTag: cb93aa94-6071-4e44-967b-72885e51d002
		dataCategory: Longitude
		summarizeBy: none
		sourceColumn: Longitud

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Ml
		dataType: double
		formatString: 0
		lineageTag: d4a8cf4c-d9a3-49cd-810e-11a65d3ebd3a
		summarizeBy: sum
		sourceColumn: Ml

		changedProperty = DataType

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isDecimal":true}

	partition MAP = m
		mode: import
		source =
				let
				    Origen = Pdf.Tables(File.Contents("F:\gustavo\Downloads\RSEC_complementos_1_a_5_def_Febrero_2015_.pdf"), [Implementation="1.3"]),
				    Table001 = Origen{[Id="Table001"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Table001, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"#", Int64.Type}, {"Año", Int64.Type}, {"Mes", Int64.Type}, {"Día", Int64.Type}, {"HH", Int64.Type}, {"MM", Int64.Type}, {"Seg", type number}, {"seg", type number}, {"L", type text}, {"Latitud", type number}, {"km", type number}, {"Longitud", type number}, {"km_1", type number}, {"Prof", type number}, {"km_2", type number}, {"NST", Int64.Type}, {"RMS", type number}, {"grados", Int64.Type}, {"Mc", type number}, {"Fuente", type text}, {"Ml", type number}, {"Fuente_3", type text}}),
				    #"Columnas con nombre cambiado" = Table.RenameColumns(#"Tipo cambiado",{{"seg", "seg.1"}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Columnas con nombre cambiado",{"Fuente_3", "Fuente", "Mc", "grados", "NST", "km_2", "km_1", "Prof", "RMS", "km", "L"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Columnas quitadas",{{"#", type text}}),
				    #"Columnas con nombre cambiado1" = Table.RenameColumns(#"Tipo cambiado1",{{"#", "ID"}}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Columnas con nombre cambiado1",{{"Año", type text}, {"Mes", type text}, {"Día", type text}}),
				    #"Filas en blanco eliminadas" = Table.SelectRows(#"Tipo cambiado2", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null})))
				in
				    #"Filas en blanco eliminadas"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

