table 'TRVA 201502 E N Z_datos_eventos_detectados'
	lineageTag: 24233d64-e12c-4230-9ac3-c447d3aac078

	column E
		dataType: int64
		formatString: 0
		lineageTag: 8baf95c4-ff56-43f8-8206-7e569d7ec9ac
		summarizeBy: none
		sourceColumn: E

		annotation SummarizationSetBy = User

	column N
		dataType: int64
		formatString: 0
		lineageTag: db1b7036-3e5e-401c-a58d-7c3d4c5ecab0
		summarizeBy: none
		sourceColumn: N

		annotation SummarizationSetBy = User

	column Z
		dataType: int64
		formatString: 0
		lineageTag: a6f100ae-9872-4e74-b62f-ba225e92c742
		summarizeBy: none
		sourceColumn: Z

		annotation SummarizationSetBy = User

	column 'timestamp.1'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 99956a1f-dcc1-4a9e-9615-755f73ac4888
		summarizeBy: none
		sourceColumn: timestamp.1

		variation Variación
			isDefault
			relationship: d462699a-cfb9-4c12-887d-039448309d9a
			defaultHierarchy: LocalDateTable_8b4f9e76-853d-4d37-9089-c9e083ab2ca8.'Jerarquía de fechas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'timestamp.2'
		dataType: dateTime
		formatString: Long Time
		lineageTag: de7ca81e-1e44-42d0-b796-a2a67e5b176f
		summarizeBy: none
		sourceColumn: timestamp.2

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Magnitud_Filtrada_MI
		dataType: int64
		formatString: 0
		lineageTag: ed024d69-2229-452f-92ec-24186b0187c9
		summarizeBy: none
		sourceColumn: Magnitud_Filtrada_MI

		annotation SummarizationSetBy = User

	column 'Inicio_Evento.2'
		dataType: dateTime
		formatString: Long Time
		lineageTag: ad09e732-d65b-43ab-9865-a50dd3ead98a
		summarizeBy: none
		sourceColumn: Inicio_Evento.2

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column 'Fin_Evento.2'
		dataType: dateTime
		formatString: Long Time
		lineageTag: c91e566f-1560-4b70-9902-cd348f95554d
		summarizeBy: none
		sourceColumn: Fin_Evento.2

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Time

	column Duracion_Evento_s
		dataType: int64
		formatString: 0
		lineageTag: 604f3fc5-e878-42b2-afcf-1a71d52a4ba8
		summarizeBy: none
		sourceColumn: Duracion_Evento_s

		annotation SummarizationSetBy = User

	partition 'TRVA 201502 E N Z_datos_eventos_detectados' = m
		mode: import
		source =
				let
				    Origen = Csv.Document(File.Contents("F:\gustavo\Desktop\PracticasProfecionalizantes_1_2025\TRVA.201502.E.N.Z_datos_eventos_detectados.csv"),[Delimiter=",", Columns=8, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Encabezados promovidos" = Table.PromoteHeaders(Origen, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"E", Int64.Type}, {"N", Int64.Type}, {"Z", Int64.Type}, {"timestamp", type datetime}, {"Magnitud_Filtrada_MI", Int64.Type}, {"Inicio_Evento", type datetime}, {"Fin_Evento", type datetime}, {"Duracion_Evento_s", Int64.Type}}),
				    #"Dividir columna por delimitador" = Table.SplitColumn(Table.TransformColumnTypes(#"Tipo cambiado", {{"timestamp", type text}}, "es-AR"), "timestamp", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"timestamp.1", "timestamp.2"}),
				    #"Tipo cambiado1" = Table.TransformColumnTypes(#"Dividir columna por delimitador",{{"timestamp.1", type date}, {"timestamp.2", type time}}),
				    #"Dividir columna por delimitador1" = Table.SplitColumn(Table.TransformColumnTypes(#"Tipo cambiado1", {{"Inicio_Evento", type text}}, "es-AR"), "Inicio_Evento", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Inicio_Evento.1", "Inicio_Evento.2"}),
				    #"Tipo cambiado2" = Table.TransformColumnTypes(#"Dividir columna por delimitador1",{{"Inicio_Evento.1", type date}, {"Inicio_Evento.2", type time}}),
				    #"Columnas quitadas" = Table.RemoveColumns(#"Tipo cambiado2",{"Inicio_Evento.1"}),
				    #"Dividir columna por delimitador2" = Table.SplitColumn(Table.TransformColumnTypes(#"Columnas quitadas", {{"Fin_Evento", type text}}, "es-AR"), "Fin_Evento", Splitter.SplitTextByDelimiter(" ", QuoteStyle.Csv), {"Fin_Evento.1", "Fin_Evento.2"}),
				    #"Tipo cambiado3" = Table.TransformColumnTypes(#"Dividir columna por delimitador2",{{"Fin_Evento.1", type date}, {"Fin_Evento.2", type time}}),
				    #"Columnas quitadas1" = Table.RemoveColumns(#"Tipo cambiado3",{"Fin_Evento.1"})
				in
				    #"Columnas quitadas1"

	annotation PBI_NavigationStepName = Navegación

	annotation PBI_ResultType = Table

